// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';
import { getStorage, connectStorageEmulator } from 'firebase/storage';
import { getAuth, connectAuthEmulator } from 'firebase/auth';

const firebaseConfig = {
  apiKey: "AIzaSyAi_hopuJB0af_OUhiPxUsrVlY0PP3oi0c",
  authDomain: "studio-8474414315-9646e.firebaseapp.com",
  projectId: "studio-8474414315-9646e",
  storageBucket: "studio-8474414315-9646e.appspot.com",
  messagingSenderId: "380046755693",
  appId: "1:380046755693:web:7862f3f35c10a976156e56"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);
const storage = getStorage(app);
const auth = getAuth(app);

if (process.env.NODE_ENV === 'development' && typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    // Point to the emulators running on localhost.
    // connectFirestoreEmulator(db, 'localhost', 8080);
    // connectStorageEmulator(storage, 'localhost', 9199);
    // connectAuthEmulator(auth, 'http://localhost:9099');
}


export { app, db, storage, auth };
