export const industries = [
  {
    name: 'Infrastructure',
    subIndustries: [
      'Civil Engineering',
      'Construction',
      'Urban Planning',
      'Public Works',
      'Water & Wastewater',
      'Solid Waste Management',
      'Telecommunications Infrastructure',
      'Transportation',
    ],
  },
  {
    name: 'Transportation',
    subIndustries: [
      'Rail Transport',
      'Road & Highway',
      'Aviation & Airports',
      'Maritime & Ports',
      'Public Transit',
      'Logistics & Freight',
      'Autonomous Vehicles',
    ],
  },
  {
    name: 'Automation',
    subIndustries: [
      'Industrial Automation',
      'Robotics',
      'Process Automation (RPA)',
      'Home Automation',
      'Building Automation',
      'Autonomous Systems',
      'Control Systems',
    ],
  },
  {
    name: 'Energy',
    subIndustries: [
      'Renewable Energy (Solar, Wind, Hydro)',
      'Fossil Fuels (Oil & Gas)',
      'Nuclear Energy',
      'Energy Storage & Batteries',
      'Grid Modernization & Smart Grids',
      'Energy Efficiency & Conservation',
      'Hydrogen Power',
    ],
  },
  { name: 'Technology', subIndustries: ['Software & SaaS', 'Hardware', 'Cybersecurity', 'AI & Machine Learning', 'Cloud Computing', 'Data Analytics', 'Internet of Things (IoT)'] },
  { name: 'Healthcare', subIndustries: ['Pharmaceuticals', 'Biotechnology', 'Medical Devices', 'Hospitals & Clinics', 'Health Insurance', 'Digital Health (Telemedicine)'] },
  { name: 'Finance', subIndustries: ['Banking', 'Investment Management', 'Insurance', 'FinTech', 'Cryptocurrency & Blockchain', 'Venture Capital'] },
  { name: 'Manufacturing', subIndustries: ['Automotive', 'Aerospace & Defense', 'Electronics', 'Heavy Machinery', 'Food & Beverage Production', '3D Printing (Additive Manufacturing)'] },
  { name: 'Retail', subIndustries: ['E-commerce', 'Brick-and-Mortar', 'Fashion & Apparel', 'Consumer Electronics', 'Groceries', 'Luxury Goods'] },
  { name: 'Education', subIndustries: ['K-12 Education', 'Higher Education', 'EdTech', 'Corporate Training', 'Early Childhood Education'] },
  { name: 'Entertainment', subIndustries: ['Film & Television', 'Music', 'Video Games', 'Live Events & Sports', 'Streaming Services'] },
  { name: 'Real Estate', subIndustries: ['Residential', 'Commercial', 'Industrial', 'Property Technology (PropTech)'] },
  { name: 'Agriculture', subIndustries: ['Farming', 'AgriTech', 'Aquaculture', 'Forestry'] },
  { name: 'Hospitality', subIndustries: ['Hotels & Resorts', 'Restaurants & Bars', 'Tourism', 'Events &Conferences'] },
  { name: 'Non-Profit', subIndustries: [] },
];