
services:
  # Frontend Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: presentationpro-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ORCH_MODE=adk
      - NEXT_PUBLIC_ADK_BASE_URL=http://localhost:18088
      - ADK_BASE_URL=http://api-gateway:8088
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-50}
    depends_on:
      - api-gateway
    networks:
      - frontend-network
      - backend-network
      - database-network
    volumes:
      - uploads-data:/app/public/uploads

  # API Gateway Service (formerly orchestrator)
  api-gateway:
    build:
      context: ./adkpy
      dockerfile: Dockerfile
    container_name: presentationpro-api-gateway
    ports:
      - "18088:8088"
    environment:
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
      - ENABLE_GEMINI_IMAGE=${ENABLE_GEMINI_IMAGE:-false}
      - GEMINI_IMAGE_MODEL=${GEMINI_IMAGE_MODEL:-gemini-2.5-flash-image-preview}
      - CLARIFIER_URL=http://clarifier:10001
      - OUTLINE_URL=http://outline:10002
      - SLIDE_WRITER_URL=http://slide-writer:10003
      - CRITIC_URL=http://critic:10004
      - NOTES_POLISHER_URL=http://notes-polisher:10005
      - DESIGN_URL=http://design:10006
      - SCRIPT_WRITER_URL=http://script-writer:10007
      - RESEARCH_URL=http://research:10008
      - VISIONCV_URL=http://visioncv:9170/mcp
      - VISIONCV_AUTO_QA=true
      - DESIGN_USE_VISIONCV=true
      - RESEARCH_USE_VISIONCV=true
      - ARANGO_URL=http://arangodb:8529
    depends_on:
      - clarifier
      - outline
      - slide-writer
      - critic
      - notes-polisher
      - design
      - script-writer
      - research
      - visioncv
      - arangodb
    networks:
      - backend-network
      - database-network
    volumes:
      - uploads-data:/app/public/uploads
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8088/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3

  # Agent Services
  clarifier:
    build:
      context: .
      dockerfile: adkpy/agents/clarifier/Dockerfile
    container_name: presentationpro-clarifier
    ports:
      - "10001:10001"
    environment:
      - A2A_PORT=10001
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://clarifier:10001
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10001), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  outline:
    build:
      context: .
      dockerfile: adkpy/agents/outline/Dockerfile
    container_name: presentationpro-outline
    ports:
      - "10002:10002"
    environment:
      - A2A_PORT=10002
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://outline:10002
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10002), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  slide-writer:
    build:
      context: .
      dockerfile: adkpy/agents/slide_writer/Dockerfile
    container_name: presentationpro-slide-writer
    ports:
      - "10003:10003"
    environment:
      - A2A_PORT=10003
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://slide-writer:10003
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10003), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  critic:
    build:
      context: .
      dockerfile: adkpy/agents/critic/Dockerfile
    container_name: presentationpro-critic
    ports:
      - "10004:10004"
    environment:
      - A2A_PORT=10004
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://critic:10004
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10004), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  notes-polisher:
    build:
      context: .
      dockerfile: adkpy/agents/notes_polisher/Dockerfile
    container_name: presentationpro-notes-polisher
    ports:
      - "10005:10005"
    environment:
      - A2A_PORT=10005
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://notes-polisher:10005
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10005), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  design:
    build:
      context: .
      dockerfile: adkpy/agents/design/Dockerfile
    container_name: presentationpro-design
    ports:
      - "10006:10006"
    environment:
      - A2A_PORT=10006
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://design:10006
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10006), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  script-writer:
    build:
      context: .
      dockerfile: adkpy/agents/script_writer/Dockerfile
    container_name: presentationpro-script-writer
    ports:
      - "10007:10007"
    environment:
      - A2A_PORT=10007
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://script-writer:10007
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10007), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  research:
    build:
      context: .
      dockerfile: adkpy/agents/research/Dockerfile
    container_name: presentationpro-research
    ports:
      - "10008:10008"
    environment:
      - A2A_PORT=10008
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - PUBLIC_URL=http://research:10008
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_USER=root
      - ARANGODB_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
      - ARANGODB_DB=presentpro
    networks:
      - backend-network
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 10008), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  # VisionCV MCP Server
  visioncv:
    build:
      context: ./visioncv
      dockerfile: Dockerfile
    container_name: presentationpro-visioncv
    ports:
      - "9170:9170"
    environment:
      - VISIONCV_MCP_TRANSPORT=http
      - VISIONCV_HOST=0.0.0.0
      - VISIONCV_PORT=9170
      - VISIONCV_HTTP_PATH=/mcp
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket;s=socket.create_connection(('localhost', 9170), timeout=5);s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  # Orchestrate Agent (A2A coordinator)
  orchestrate:
    build:
      context: .
      dockerfile: adkpy/agents/orchestrate/Dockerfile
    container_name: presentationpro-orchestrate
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
      - REMOTE_AGENT_ADDRESSES=http://clarifier:10001,http://outline:10002,http://slide-writer:10003,http://critic:10004,http://notes-polisher:10005,http://design:10006,http://script-writer:10007,http://research:10008
    depends_on:
      - clarifier
      - outline
      - slide-writer
      - critic
      - notes-polisher
      - design
      - script-writer
      - research
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import pathlib; pathlib.Path('/app/adkpy/agents/orchestrate').exists()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  # ADK Dev UI Service
  dev-ui:
    build:
      context: ./adkpy
      dockerfile: Dockerfile.devui
    container_name: presentationpro-dev-ui
    ports:
      - "8100:8100"
    environment:
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_GENAI_API_KEY}
    depends_on:
      - clarifier
      - outline
      - slide-writer
      - critic
      - notes-polisher
      - design
      - script-writer
      - research
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8100/')\""]
      interval: 30s
      timeout: 5s
      retries: 3

  # Database Service
  arangodb:
    image: arangodb:latest
    container_name: presentationpro-arangodb
    ports:
      - "8530:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD:-root}
    volumes:
      - arangodb-data:/var/lib/arangodb3
      - arangodb-apps:/var/lib/arangodb3-apps
    networks:
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "arangosh --server.endpoint tcp://127.0.0.1:8529 --server.username root --server.password ${ARANGO_ROOT_PASSWORD:-root} --server.database _system --server.request-timeout 5 --javascript.execute-string \"db._version();\""]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  database-network:
    driver: bridge

volumes:
  arangodb-data:
  arangodb-apps:
  uploads-data:


