// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to generate a presentation outline based on the clarified content from the chat.
 *
 * - generatePresentationOutline - A function that handles the generation of the presentation outline.
 * - GeneratePresentationOutlineInput - The input type for the generatePresentationOutline function.
 * - GeneratePresentationOutlineOutput - The return type for the generatePresentationOutline function.
 */

// import {ai} from '@/ai.deprecated_genkit/genkit'; // Archived - do not use
import {z} from 'genkit';

const GeneratePresentationOutlineInputSchema = z.object({
  clarifiedContent: z
    .string()
    .describe('The clarified content from the chat, providing context for the presentation outline.'),
});
export type GeneratePresentationOutlineInput = z.infer<typeof GeneratePresentationOutlineInputSchema>;

const GeneratePresentationOutlineOutputSchema = z.object({
  slideTitles: z
    .array(z.string())
    .describe('An array of slide titles representing the presentation outline.'),
});
export type GeneratePresentationOutlineOutput = z.infer<typeof GeneratePresentationOutlineOutputSchema>;

export async function generatePresentationOutline(
  input: GeneratePresentationOutlineInput
): Promise<GeneratePresentationOutlineOutput> {
  return generatePresentationOutlineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePresentationOutlinePrompt',
  input: {schema: GeneratePresentationOutlineInputSchema},
  output: {schema: GeneratePresentationOutlineOutputSchema},
  prompt: `You are an expert presentation designer.

  Based on the clarified content provided, generate a logical and coherent slide outline for a presentation.
  The outline should consist of an array of slide titles that cover the key points and flow logically.

  Use the following context about what makes a great presentation to inform your outline structure.
  START OF CONTEXT
  The Orator's Crucible: An Analytical History of the World's Greatest Presenters
Introduction: The Anatomy of Oratorical Excellence
The capacity to stand before an audience and, through the power of the spoken word, alter perspectives, inspire action, or reshape the course of history is one of humanity's most formidable skills. From the stone assemblies of ancient Athens to the glowing stages of the digital age, the principles of effective presentation have been studied, codified, and revered. This report undertakes a comprehensive analysis of history's most masterful presenters, examining not only their celebrated performances but also the intricate machinery of their methods, the philosophical underpinnings of their communication, and the core personality traits that animated their public personae.

To establish a consistent framework for this longitudinal study, it is essential to define the universal components of oratorical mastery. A synthesis of rhetorical theory and modern communication science reveals a set of core competencies that transcend time and technology. First and foremost is Audience Centricity, the profound ability to analyze an audience—their beliefs, their fears, their needs—and meticulously tailor the message to resonate with them. This is intrinsically linked to    

Narrative Structure, the art of "telling a story" with a clear purpose, a logical flow, and a compelling call to action that provides the audience with a clear destination.   

Beyond structure lies the crucial element of Emotional Resonance, the classical concept of pathos. This is the presenter's capacity to forge a genuine connection, build rapport, and stir the emotions of the audience through expressive vocal tones, deliberate body language, and evocative storytelling. This connection is fortified by    

Credibility and Confidence, or ethos, the projection of authority, authenticity, and control that engenders trust and makes a message believable. Finally, these elements must be built upon a foundation of    

Clarity and Logic—logos—a well-reasoned, content-rich argument that is both persuasive and easy to comprehend. _BAR_ 

A central theme that emerges from the study of these masters is the fundamental fallacy of the "natural-born orator." The historical record consistently demonstrates that oratorical excellence is not a gift bestowed by nature but a craft forged in the crucible of deliberate, often obsessive, practice. Figures who are often mythologized for their innate genius are, upon closer inspection, revealed to be paragons of industry who overcame significant personal and professional obstacles. This suggests that the single most important trait of a great presenter is not effortless charisma, but an unyielding determination to master the art of communication. Their greatness was not born; it was made.

Chapter 1: The Founders of Persuasion - Orators of Ancient History
The classical world established a foundational principle that endures to this day: effective public speaking is not mere performance but a deeply intellectual, strategic, and civic discipline. The codification of rhetoric by figures like Cicero was not an abstract academic pursuit but the creation of a practical toolkit for wielding influence and power within the state. For the ancients, oratory was inseparable from statecraft and intellectual rigor, a stark contrast to modern perceptions of public speaking as a "soft skill." They viewed communication as the central pillar of governance. This understanding was sharpened by the high-stakes environment in which they operated. The greatest orators of antiquity were defined by their responses to profound personal and political crises. Demosthenes honed his skills to defend Athens from existential threat, while Cicero delivered his most famous speeches to protect the Republic from internal conspiracy. This pattern reveals that the pressure of crisis forces a clarity of purpose and an emotional intensity that forges transcendent oratory, a dynamic that would reappear centuries later in the speeches of wartime leaders and revolutionaries.   

Socrates: The Presenter as Inquisitor
Socrates (c. 470–399 BCE) revolutionized the concept of public discourse by transforming it from a monologue of pronouncements into a dynamic, interactive dialogue. He presented not by lecturing, but by questioning.

Techniques and Style
Socrates's singular technique was the Socratic Method, or elenchus—a disciplined, argumentative dialogue designed to scrutinize deeply held beliefs through relentless inquiry. In practice, this involved the instructor feigning ignorance of a topic to engage students or interlocutors in a shared exploration of a concept. His "presentations" were co-created in real time with his audience, a back-and-forth exchange where he would pose a thought-provoking question, elicit a response, and then use further questions to dissect that response, exposing its underlying assumptions and inconsistencies. This method was highly active and participatory, demanding that his "audience" become collaborators in the pursuit of knowledge.   

Philosophy and Preparation
Socrates's philosophy of communication was predicated on the belief that true knowledge is not transmitted from teacher to student but is discovered within the self through rigorous examination. He believed that "all thinking comes from asking questions" and that the goal of dialogue was not to win an argument but to achieve a shared, more coherent understanding of moral and ethical truths. His preparation, therefore, was not about memorizing a speech but about formulating the perfect initial question—one that was concrete and relatable to his students' experiences—and then anticipating the logical pathways and subsidiary questions that would guide the conversation toward its conclusion. _BAR_ 

Personality and Persona
Socrates's public persona was that of an intellectually humble yet persistently curious questioner. He subverted the traditional role of the "sage on the stage," instead presenting himself as an explorer ignorant of the final destination but expert in navigating the journey. This persona, famously captured in Plato's dialogues, was enigmatic and often infuriating to his contemporaries, as his method relentlessly exposed the intellectual complacency of Athens's prominent citizens. His personality was defined by an absolute commitment to intellectual honesty and self-examination, a conviction so profound that he ultimately chose execution over abandoning his public mission of inquiry.   

Demosthenes: Forging Eloquence Through Sheer Will
Demosthenes (384–322 BCE) stands as the ultimate testament to the power of perseverance in the face of profound natural limitations. His journey from a physically frail youth with a debilitating speech impediment to the greatest orator of ancient Athens exemplifies the principle that mastery is a product of industry, not innate genius.

Techniques and Style
Demosthenes was renowned for a vigorous, astute, and intensely passionate style that could seamlessly blend different rhetorical approaches to suit his purpose. He was a master of engaging his audience directly, famously using rhetorical questions to create a sense of shared urgency and deliberation, as in his    

Philippics against the Macedonian king: "Will you still ask, Athenians, what Philip is doing?". He employed repetition and parallel structures to emphasize key points and build momentum toward a powerful call to action. His speeches were not abstract exercises in eloquence; they were practical, patriotic, and urgent appeals framed around the core themes of Athenian liberty and the dire consequences of political apathy and inaction. _BAR_ 

Philosophy and Preparation
Demosthenes's entire philosophy of communication was forged by his early, humiliating failures in the Athenian Assembly, where he was derided for his "perplexed and indistinct utterance and a shortness of breath". This led him to the conviction that oratorical power was owed entirely to "labor and industry". His preparation was the stuff of legend—an obsessive, all-consuming regimen designed to re-engineer his physical capabilities. He practiced speaking with pebbles in his mouth to correct his stammer, declaimed verses while running uphill to strengthen his breath control, and shouted over the roar of the sea to increase his vocal power. So that he would not be tempted to leave his studies, he built an underground chamber and shaved half his head, ensuring his humiliating appearance would confine him to his practice for months at a time. This extreme discipline reflected a philosophy of total preparation; he was known to be reluctant to speak extemporaneously, preferring to have every argument meticulously studied and rehearsed.   

Personality and Persona
Demosthenes's personality was defined by an almost superhuman determination and a fierce, unwavering patriotism. His life story is one of overcoming immense personal obstacles through sheer force of will, a narrative that undoubtedly informed his public persona. In the Assembly, he projected an image of passionate and forceful conviction, becoming the leading voice of resistance against Macedonian expansionism. He was the embodiment of his message: a figure who, like Athens itself, could rise from a state of weakness to one of formidable strength through vigilance and effort.   

Cicero: The Architect of Rhetoric
Marcus Tullius Cicero (106–43 BCE) was not only Rome's greatest orator but also its most important theorist of the art. He systematically codified the principles of persuasion, creating a comprehensive framework that has influenced Western thought for over two millennia.

Techniques and Style
Cicero's style was marked by its versatility and adaptability. He was a master of all three of Aristotle's modes of persuasion: logos (logic and reason), pathos (emotional appeal), and ethos (credibility and character). His delivery was a model of controlled power; he modulated his voice across a full scale of tones and used gestures that were impressive and erect but never extravagant. He could be rigorously logical in a legal case or powerfully emotional in a political speech, as demonstrated in his    

Catiline Orations, where he masterfully played on the Senate's fear of conspiracy to expose and condemn his adversary. His prose was celebrated for its clarity, rhythm, and persuasive force.   

Philosophy and Preparation
Cicero's most enduring contribution was his systematization of rhetoric into what became known as the five canons: Inventio (the discovery of arguments), Dispositio (the arrangement of arguments), Elocutio (the style and language), Memoria (memorization), and Pronuntiatio (delivery). This framework reveals his philosophy that a great presentation is a holistic creation, requiring as much intellectual labor in preparation as performative skill in delivery. He argued that the ideal orator must be a person of immense learning, possessing an "encyclopedic knowledge" and combining "the subtlety of the logician, the thoughts of the philosopher, a diction almost poetic... and the bearing almost of the consummate actor". His ultimate goal was to    

docere, delectare, et movere—to teach, to delight, and to move the audience emotionally, recognizing that logic alone was insufficient for true persuasion. This philosophy was backed by an incredible work ethic; he was known for his industriousness, conducting thorough research and working late into the night to master his subjects.   

Personality and Persona
Cicero's personality was a complex mixture of ambition, intellectual brilliance, and principled conviction. He was a staunch defender of the Roman Republic, a value for which he ultimately paid with his life. He was also remarkably self-aware, admitting in his writings to feeling "very nervous when I begin to speak," viewing each oration as a profound judgment not just of his ability but of his "character and honor". On the public stage, he projected a persona of supreme authority and intellect. Yet he was also a master of what modern scholars call "self-fashioning," capable of strategically adopting different personae—the fierce attacker, the loyal friend, the noble martyr—to navigate the treacherous political landscape of the late Republic.   

[Additional content truncated for brevity]

  END OF CONTEXT

  Clarified content: {{clarifiedContent}}

  Create a thoughtful outline (between 6-12 slides) that tells a compelling story.`,
});

const generatePresentationOutlineFlow = ai.defineFlow(
  {
    name: 'generatePresentationOutlineFlow',
    inputSchema: GeneratePresentationOutlineInputSchema,
    outputSchema: GeneratePresentationOutlineOutputSchema,
  },
  async input => {
    const response = await prompt(input);
    return response;
  }
);